baseurl = "http://anthonyrhowell.com/"
languageCode = "en-us"
title = "Tony Howell"
theme = "hugo-type-theme"
# Enable comments by entering your Disqus shortname
disqusShortname = "anthonyrhowell"
# Add your tracking code to enable Google Analytics
googleAnalytics = ""
# Posts per page
paginate = 10


[params]
	author = "Tony Howell"
	description = "Coding and things"
	# Either show custom avatar on the top
	# left by adding the filename in below
	# avatar = "img/avatar.png"
	# or use Gravatar by adding an MD5-hash of your email address
	gravatar = "e06b6c17814fc12ebf9a13d7aa423b4d"

	headerText = "Coding and things."
	# To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	# headerImage = ""
	# copyright = "Released under the MIT license<br>Powered by [Hugo](//gohugo.io/) with the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)"


	[params.social]
	# Insert your accout name and the icon will be shown in the right menu
		rss = true
		email = "tony@arh.email"
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "tonycapone"
		googleplus = ""
		instagram = ""
		linkedin = "https://www.linkedin.com/in/tony-howell-262a212a"
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = ""
		wordpress = ""
		youtube = ""
